default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: samuelkuria
  password: techisthefuture002
  host: localhost

development:
  <<: *default
  database: dbname_development

test:
  <<: *default
  database: dbname_test

production:
  <<: *default
  database: dbname_production
